### ISSUE TITLE
It doesn't work on macos idea

### ISSUE THREAD

**Issue by lvsecoto** [nEdAy/Flutter-Build-Runner-Helper#1]
Hi, this plugin is greated. But I found issue it doesn't work...
```
flutter packages pub run build_runner build --delete-conflicting-outputs

The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "pub get" again.
pub finished with exit code 65
build_runner Error! Exit with code: 65
```

I have already run `flutter pub get`. 
And if I run `flutter packages pub run build_runner build --delete-conflicting-outputs` in terminal, it works.

**Comment by nEdAy** [comment]
Thank you for your feedback.
I also debugged this plug-in under Android Studio with Mac.

According to the tip, since you changed "pubspec.yaml, you need to run "flutter pub get" before you can use "build_runner".

Click "Build" again and the error will still appear:

`
[SEVERE] Conflicting outputs were detected and the build is unable to prompt for permission to remove them. These outputs must be removed manually or the build can be run with `--delete-conflicting-outputs`.`

At this point, you need to execute ’flutter packages pub run build_runner build --delete-conflicting-outputs‘.
After that, everything was fine.

Clicking the ’rebuild‘ icon in the toolbar is equivalent to executing ’flutter packages pub run build_runner build --delete-conflicting-outputs‘.

**Comment by lvsecoto** [comment]
I have run `flutter packages pub run build_runner build  --delete-conflicting-outputs`, and sample problem appears...

Here is my Android Studio version:
> Android Studio 4.0
> Build #AI-193.6911.18.40.6514223, built on May 20, 2020
> Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> macOS 10.14.5
> GC: ParNew, ConcurrentMarkSweep
> Memory: 2014M
> Cores: 4
> Registry: ide.new.welcome.screen.force=true, ide.balloon.shadow.size=0
> Non-Bundled Plugins: Dart, IdeaVIM, cn.neday.excavator, cn.yiiguxing.plugin.translate, com.chrisrm.idea.MaterialThemeUI, com.dvd.intellijdea.materialcolorpalette, com.potterhsu.jsonviewer, com.ppolivka.gitlabprojects, com.vladsch.idea.multimarkdown, io.flutter, de.mariushoefler.flutter_enhancement_suite, mobi.hsz.idea.gitignore, org.intellij.RegexpTester, org.toml.lang, ru.trylogic.idea.gitlab.integration

**Comment by nEdAy** [comment]
The latest version of this plugin is v1.5.
https://plugins.jetbrains.com/plugin/14442-flutter-build-runner-helper

This plugin is just instead of manually executing commands in the terminal.
It has the same effect as executing a command in a terminal, and if something goes wrong, follow the build_runner output.

My Android Studio version:

Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.new.welcome.screen.force=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Dart, Sexy Editor, cat.kanbanapps.gradlekiller, cn.neday.excavator, com.chrisrm.idea.MaterialThemeUI, com.developerphil.adbidea, com.github.hayoi.haystack, com.herbert.george.flutter-snippets, com.khch.restful.tool, com.shenyong.flutter.refgenerator, com.weirddev.testme, io.flutter, org.liujing.plugin.json_serializable_format, some.awesme, wu.seal.tool.jsontokotlin

**Comment by nEdAy** [comment]
`build_runner: ^1.10.0`

```
flutter --version
Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b041144f83 (3 weeks ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```
