### ISSUE TITLE
Actions not showing on toolbar.

### ISSUE THREAD

**Issue by Charlie-sHub** [nEdAy/Flutter-Build-Runner-Helper#11]
The actions simple don't appear on the toolbars of Android Studio, neither the Navigation Bar Toolbar not the Main Toolbar, they appear as added on  Settings > Appearance & Behavior > Menus And Toolbars, but they don't appear at all in the actual toolbars, unless i add the whole folder, then a circle with a ? appears on the toolbar but it's greyed out and completely useless. I've tried reinstalling the plugin, removing and reading manually, but nothing works.

I seem to be the only one with the issue as i've seen nothing similar looking trough the internet, i'm thinking it might be an issue on my end though, maybe it's some config file i've no idea of.

**Comment by nEdAy** [comment]
Thanks for using.
This is probably because your Android Studio does not open a Flutter project.
The Action icon of the plugin is only displayed under the Flutter project.
"ProjectChecker.kt" detects the directory structure of the current project.
`    private var checkFiles: ArrayList<String> = arrayListOf("lib", ".metadata", ".packages", "pubspec.lock", "pubspec.yaml")
`

If this is not the case, make sure you are using the latest version of the plugin, and let me know which version of Android Studio you use.

**Comment by Charlie-sHub** [comment]
"This is probably because your Android Studio does not open a Flutter project"
Makes sense since new flutter projects do work, the actions appear i mean.
I messed around and re-imported the project, it works now.
Thanks.
